
-- College Placement Analytics System
-- Database Table Creation


CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    department VARCHAR2(50) NOT NULL,
    graduation_year NUMBER(4) NOT NULL,
    cgpa NUMBER(3,2)
);

CREATE TABLE companies (
    company_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(100) NOT NULL,
    industry VARCHAR2(100),
    location VARCHAR2(100),
    company_type VARCHAR2(50)
);

CREATE TABLE job_roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id NUMBER NOT NULL,
    role_name VARCHAR2(100) NOT NULL,
    minimum_cgpa NUMBER(3,2),
    package_lpa NUMBER(5,2),
    CONSTRAINT fk_role_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
);

CREATE TABLE skills (
    skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR2(100) UNIQUE NOT NULL,
    skill_category VARCHAR2(50)
);

CREATE TABLE student_skills (
    student_id NUMBER NOT NULL,
    skill_id NUMBER NOT NULL,
    CONSTRAINT pk_student_skills
        PRIMARY KEY (student_id, skill_id),
    CONSTRAINT fk_ss_student
        FOREIGN KEY (student_id)
        REFERENCES students(student_id),
    CONSTRAINT fk_ss_skill
        FOREIGN KEY (skill_id)
        REFERENCES skills(skill_id)
);

CREATE TABLE job_role_skills (
    role_id NUMBER NOT NULL,
    skill_id NUMBER NOT NULL,
    CONSTRAINT pk_job_role_skills
        PRIMARY KEY (role_id, skill_id),
    CONSTRAINT fk_jrs_role
        FOREIGN KEY (role_id)
        REFERENCES job_roles(role_id),
    CONSTRAINT fk_jrs_skill
        FOREIGN KEY (skill_id)
        REFERENCES skills(skill_id)
);

CREATE TABLE applications (
    application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    application_date DATE DEFAULT SYSDATE,
    status VARCHAR2(30) DEFAULT 'Applied',
    CONSTRAINT fk_app_student
        FOREIGN KEY (student_id)
        REFERENCES students(student_id),
    CONSTRAINT fk_app_role
        FOREIGN KEY (role_id)
        REFERENCES job_roles(role_id)
);

CREATE TABLE interviews (
    interview_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER NOT NULL,
    round_name VARCHAR2(50) NOT NULL,
    interview_date DATE,
    result VARCHAR2(30),
    CONSTRAINT fk_interview_application
        FOREIGN KEY (application_id)
        REFERENCES applications(application_id)
);

CREATE TABLE offers (
    offer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER NOT NULL,
    offer_date DATE DEFAULT SYSDATE,
    package_lpa NUMBER(5,2),
    joining_location VARCHAR2(100),
    offer_status VARCHAR2(30) DEFAULT 'Accepted',
    CONSTRAINT fk_offer_application
        FOREIGN KEY (application_id)
        REFERENCES applications(application_id)
);